server {
  listen 3000;
  resolver 127.0.0.11 valid=30s;
  
  location /api/ {
    set $backendApi "http://api-gateway:3000";
    proxy_pass $backendApi;
  }

  location / {
    set $frontendApp "http://todo-app:3000";
    proxy_pass $frontendApp;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
